use serde::Serialize;
use crate::report::model::{Category, Severity};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct RuleInfo {
    pub id: &'static str,
    pub name: &'static str,
    pub severity: Severity,
    pub category: Category,
    pub title: &'static str,
    pub description: &'static str,
    pub agents: &'static [&'static str],
    pub references: &'static [&'static str],
}

#[derive(Debug, Clone, Serialize)]
pub struct RulesCatalog {
    pub version: String,
    pub rules: Vec<RuleInfo>,
}

pub const RULES: &[RuleInfo] = &[
    RuleInfo {
        id: "PT-GIT-001",
        name: "GitFsMonitor",
        severity: Severity::Critical,
        category: Category::GitExecutionSink,
        title: "Git core.fsmonitor command execution sink",
        description: "Executes arbitrary commands via core.fsmonitor on git status/diff operations before workspace trust.",
        agents: &["Git", "Claude Code", "Cursor", "Codex"],
        references: &["https://labs.cloudsecurityalliance.org/research/csa-research-note-ai-coding-agent-git-config-rce-20260904-cs/"],
    },
    RuleInfo {
        id: "PT-GIT-002",
        name: "GitHooksPath",
        severity: Severity::Critical,
        category: Category::GitExecutionSink,
        title: "Git core.hooksPath override",
        description: "Redirects git hook execution to an arbitrary repository or external path.",
        agents: &["Git", "Claude Code", "Cursor", "Codex"],
        references: &["https://nvd.nist.gov/vuln/detail/CVE-2026-26268"],
    },
    RuleInfo {
        id: "PT-GIT-003",
        name: "GitDiffExternal",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git diff.external execution sink",
        description: "Specifies an external command executed whenever git diff runs.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-diffexternal"],
    },
    RuleInfo {
        id: "PT-GIT-004",
        name: "GitDiffTextconv",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git diff textconv filter execution",
        description: "Executes custom binary to convert binary files to text during git diff.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-diffdrivertextconv"],
    },
    RuleInfo {
        id: "PT-GIT-005",
        name: "GitDiffCommand",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git diff driver command execution",
        description: "Executes custom driver binary during git diff operations.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-diffdrivercommand"],
    },
    RuleInfo {
        id: "PT-GIT-006",
        name: "GitFilterClean",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git filter driver clean execution",
        description: "Runs custom command when staging files to git index.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-filterdriverclean"],
    },
    RuleInfo {
        id: "PT-GIT-007",
        name: "GitFilterSmudge",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git filter driver smudge execution",
        description: "Runs custom command when checking out files from git repository.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-filterdriversmudge"],
    },
    RuleInfo {
        id: "PT-GIT-008",
        name: "GitFilterProcess",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git filter driver process execution",
        description: "Spawns long-running filter process communicating over stdin/stdout during git checkout.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-filterdriverprocess"],
    },
    RuleInfo {
        id: "PT-GIT-009",
        name: "GitSshCommand",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git core.sshCommand binary override",
        description: "Overrides SSH command binary executed during remote git network operations.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand"],
    },
    RuleInfo {
        id: "PT-GIT-010",
        name: "GitConfigIncludeSmuggling",
        severity: Severity::High,
        category: Category::ConfigurationSmuggling,
        title: "Git configuration external include smuggling",
        description: "Includes git configuration from outside the repository tree.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#_includes"],
    },
    RuleInfo {
        id: "PT-GIT-011",
        name: "GitConfigIncludeSmuggling",
        severity: Severity::High,
        category: Category::ConfigurationSmuggling,
        title: "Git configuration excessive include depth",
        description: "Excessive nesting depth of git configuration includes indicating smuggling.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#_includes"],
    },
    RuleInfo {
        id: "PT-GIT-012",
        name: "GitConfigCircularInclude",
        severity: Severity::High,
        category: Category::ConfigurationSmuggling,
        title: "Git configuration circular include loop",
        description: "Circular inclusion chain in repository git configuration.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#_includes"],
    },
    RuleInfo {
        id: "PT-GIT-013",
        name: "GitCredentialHelper",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git credential.helper process execution",
        description: "Executes helper process or shell command during credential retrieval.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-credentialhelper"],
    },
    RuleInfo {
        id: "PT-GIT-014",
        name: "GitUrlInsteadOf",
        severity: Severity::Critical,
        category: Category::GitExecutionSink,
        title: "Git url.insteadOf unneutralizable redirection",
        description: "Rewrites remote repository URLs to hijack git fetch and push operations.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlbaseinsteadOf"],
    },
    RuleInfo {
        id: "PT-GIT-015",
        name: "GitShellAlias",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Git alias command execution",
        description: "Defines git alias prefixed with ! that executes arbitrary shell commands.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/git-config#Documentation/git-config.txt-alias"],
    },
    RuleInfo {
        id: "PT-GIT-020",
        name: "GitActiveAttributeDriverJoin",
        severity: Severity::High,
        category: Category::GitExecutionSink,
        title: "Active driver bound in .gitattributes",
        description: "Gitattributes binds files to custom execution filter or diff drivers.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/gitattributes"],
    },
    RuleInfo {
        id: "PT-GIT-021",
        name: "GitDormantAttributeDriver",
        severity: Severity::Low,
        category: Category::GitExecutionSink,
        title: "Dormant driver defined in git config",
        description: "Custom driver configured in git config but not currently bound in .gitattributes.",
        agents: &["Git", "Claude Code", "Cursor"],
        references: &["https://git-scm.com/docs/gitattributes"],
    },
    RuleInfo {
        id: "PT-PROV-001",
        name: "GitProvenanceAssembledArchive",
        severity: Severity::Medium,
        category: Category::RepositoryProvenance,
        title: "Assembled repository archive lacking provenance",
        description: "Repository lacks reflog history and remote tracking branches, indicating an assembled archive.",
        agents: &["Git"],
        references: &["https://git-scm.com/docs/git-reflog"],
    },
    RuleInfo {
        id: "PT-TASK-001",
        name: "VSCodeTasksFolderOpen",
        severity: Severity::Critical,
        category: Category::WorkspaceAutoRun,
        title: "VS Code task auto-executes on folderOpen",
        description: "Configures automatic task execution upon opening workspace folder.",
        agents: &["VS Code", "Copilot"],
        references: &["https://code.visualstudio.com/docs/editor/tasks"],
    },
    RuleInfo {
        id: "PT-CARGO-001",
        name: "CargoRustcWrapper",
        severity: Severity::High,
        category: Category::WorkspaceAutoRun,
        title: "Cargo build rustc-wrapper execution hook",
        description: "Cargo configuration specifies custom rustc-wrapper executed during cargo check and build.",
        agents: &["Cargo", "Rust"],
        references: &["https://doc.rust-lang.org/cargo/reference/config.html#buildrustc-wrapper"],
    },
    RuleInfo {
        id: "PT-CARGO-002",
        name: "CargoTargetRunner",
        severity: Severity::High,
        category: Category::WorkspaceAutoRun,
        title: "Cargo target runner execution hook",
        description: "Cargo target configuration specifies custom runner executed during cargo run and test.",
        agents: &["Cargo", "Rust"],
        references: &["https://doc.rust-lang.org/cargo/reference/config.html#targettriplerunner"],
    },
    RuleInfo {
        id: "PT-INST-001",
        name: "AgentInstructionZeroWidthSmuggling",
        severity: Severity::Critical,
        category: Category::PromptInjection,
        title: "Zero-width unicode smuggling in agent instructions",
        description: "Hides malicious prompt injection instructions using invisible zero-width unicode characters.",
        agents: &["Claude Code", "Cursor", "Copilot", "Gemini CLI"],
        references: &["https://owasp.org/www-project-top-10-for-large-language-model-applications/"],
    },
    RuleInfo {
        id: "PT-INST-002",
        name: "AgentInstructionAnsiSmuggling",
        severity: Severity::High,
        category: Category::PromptInjection,
        title: "ANSI escape sequence smuggling in agent instructions",
        description: "Smuggles instructions or terminal escapes via ANSI sequences in markdown instruction files.",
        agents: &["Claude Code", "Cursor", "Copilot", "Gemini CLI"],
        references: &["https://owasp.org/www-project-top-10-for-large-language-model-applications/"],
    },
    RuleInfo {
        id: "PT-INST-003",
        name: "AgentInstructionPromptInjection",
        severity: Severity::High,
        category: Category::PromptInjection,
        title: "Prompt injection phrase in agent instructions",
        description: "Agent instruction file contains explicit prompt override or exfiltration commands.",
        agents: &["Claude Code", "Cursor", "Copilot", "Gemini CLI"],
        references: &["https://owasp.org/www-project-top-10-for-large-language-model-applications/"],
    },
    RuleInfo {
        id: "PT-LOCK-001",
        name: "LockfileHashMismatch",
        severity: Severity::Critical,
        category: Category::PromptInjection,
        title: "Lockfile drift: instruction or config hash mismatch",
        description: "Monitored agent configuration file has been modified since pretrust.lock fingerprint was recorded.",
        agents: &["Pretrust"],
        references: &["https://github.com/aliefe04/pretrust"],
    },
    RuleInfo {
        id: "PT-LOCK-002",
        name: "LockfileMissingFile",
        severity: Severity::High,
        category: Category::PromptInjection,
        title: "Lockfile drift: locked file removed",
        description: "Monitored configuration file recorded in pretrust.lock was deleted from repository.",
        agents: &["Pretrust"],
        references: &["https://github.com/aliefe04/pretrust"],
    },
    RuleInfo {
        id: "PT-LOCK-003",
        name: "LockfileUntrackedNewFile",
        severity: Severity::High,
        category: Category::PromptInjection,
        title: "Lockfile drift: new untracked instruction or config file",
        description: "New agent instruction or configuration file introduced without being recorded in pretrust.lock.",
        agents: &["Pretrust"],
        references: &["https://github.com/aliefe04/pretrust"],
    },
    RuleInfo {
        id: "PT-MCP-001",
        name: "McpPromptInjection",
        severity: Severity::Critical,
        category: Category::PromptInjection,
        title: "MCP server description prompt injection",
        description: "MCP server description contains hidden zero-width characters or prompt injection override phrases.",
        agents: &["Cursor", "Claude Code", "VS Code", "Gemini CLI"],
        references: &["https://owasp.org/www-project-top-10-for-large-language-model-applications/"],
    },
    RuleInfo {
        id: "PT-MCP-002",
        name: "McpUnpinnedPackage",
        severity: Severity::Medium,
        category: Category::UnpinnedDependency,
        title: "MCP server uses unpinned package version",
        description: "MCP server configuration references latest or unpinned package, vulnerable to upstream dependency compromise.",
        agents: &["Cursor", "Claude Code", "VS Code", "Gemini CLI"],
        references: &["https://cwe.mitre.org/data/definitions/829.html"],
    },
    RuleInfo {
        id: "PT-MCP-003",
        name: "McpRepoLocalCommand",
        severity: Severity::High,
        category: Category::McpExecutionSink,
        title: "MCP server executes repo-local binary or inline shell",
        description: "Stdio MCP server command or args run an untrusted repo file or inline shell script.",
        agents: &["Cursor", "Claude Code", "VS Code", "Zed", "Amazon Q", "Gemini CLI"],
        references: &[
            "https://nvd.nist.gov/vuln/detail/CVE-2025-64109",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-54136",
        ],
    },
    RuleInfo {
        id: "PT-MCP-004",
        name: "GeminiProjectMcpServer",
        severity: Severity::Critical,
        category: Category::McpExecutionSink,
        title: "Gemini CLI project stdio MCP server auto-execution",
        description: "Project .gemini/settings.json defines stdio MCP server which executes without folder trust prompt by default.",
        agents: &["Gemini CLI"],
        references: &["https://geminicli.com/docs/cli/trusted-folders.md"],
    },
    RuleInfo {
        id: "PT-MCP-005",
        name: "McpHardcodedSecret",
        severity: Severity::High,
        category: Category::SecretExposure,
        title: "Hardcoded secret in MCP server env or headers",
        description: "Literal credentials or API keys embedded in MCP server environment variables or request headers.",
        agents: &["Cursor", "Claude Code", "VS Code", "Zed", "Amazon Q", "Gemini CLI"],
        references: &["https://cwe.mitre.org/data/definitions/798.html"],
    },
    RuleInfo {
        id: "PT-MCP-006",
        name: "McpInsecureRemote",
        severity: Severity::Medium,
        category: Category::McpExecutionSink,
        title: "Insecure unencrypted HTTP remote MCP endpoint",
        description: "Remote MCP server endpoint connects over unencrypted plain HTTP to a non-loopback host.",
        agents: &["Cursor", "Claude Code", "VS Code", "Gemini CLI"],
        references: &["https://cwe.mitre.org/data/definitions/319.html"],
    },
    RuleInfo {
        id: "PT-HOOK-001",
        name: "ClaudeSettingsHook",
        severity: Severity::High,
        category: Category::AgentLifecycleHook,
        title: "Claude settings automated lifecycle hook",
        description: "Automated lifecycle hook configured in .claude/settings.json executes arbitrary shell commands.",
        agents: &["Claude Code"],
        references: &["https://code.claude.com/docs/en/hooks.md"],
    },
    RuleInfo {
        id: "PT-HOOK-002",
        name: "CursorLifecycleHook",
        severity: Severity::High,
        category: Category::AgentLifecycleHook,
        title: "Cursor automated lifecycle hook",
        description: "Automated workspace lifecycle hook configured in .cursor/hooks.json executes commands without prompt.",
        agents: &["Cursor"],
        references: &["https://cursor.com/docs/hooks.md"],
    },
    RuleInfo {
        id: "PT-CLAUDE-001",
        name: "ClaudeEnvOverride",
        severity: Severity::Critical,
        category: Category::AgentEnvironmentOverride,
        title: "Claude settings sensitive environment variable override",
        description: "Overrides critical environment variables such as ANTHROPIC_BASE_URL, HTTP_PROXY, or LD_PRELOAD in Claude settings.",
        agents: &["Claude Code"],
        references: &["https://nvd.nist.gov/vuln/detail/CVE-2026-21852"],
    },
    RuleInfo {
        id: "PT-CLAUDE-002",
        name: "ClaudeCommandHelper",
        severity: Severity::High,
        category: Category::AgentLifecycleHook,
        title: "Claude settings automated command helper",
        description: "Configures automated command helpers such as apiKeyHelper, statusLine.command, or awsAuthRefresh.",
        agents: &["Claude Code"],
        references: &["https://code.claude.com/docs/en/settings-reference.md"],
    },
    RuleInfo {
        id: "PT-CLAUDE-003",
        name: "ClaudeMcpAutoApprove",
        severity: Severity::High,
        category: Category::AgentPermissionOverride,
        title: "Claude settings automated MCP server approval",
        description: "Enables automatic approval of all project MCP servers bypassing interactive user confirmation.",
        agents: &["Claude Code"],
        references: &["https://code.claude.com/docs/en/permissions.md"],
    },
    RuleInfo {
        id: "PT-CLAUDE-004",
        name: "ClaudePermissiveMode",
        severity: Severity::High,
        category: Category::AgentPermissionOverride,
        title: "Claude settings permissive bypass or blanket shell execution",
        description: "Configures bypassPermissions defaultMode or blanket wildcard Bash execution permissions.",
        agents: &["Claude Code"],
        references: &["https://code.claude.com/docs/en/permissions.md"],
    },
    RuleInfo {
        id: "PT-CURSOR-001",
        name: "CursorCliPermissions",
        severity: Severity::High,
        category: Category::AgentPermissionOverride,
        title: "Cursor CLI pre-approved shell or write permissions",
        description: "Grants pre-approved Shell() or Write() permissions via repository .cursor/cli.json without user prompt.",
        agents: &["Cursor"],
        references: &["https://nvd.nist.gov/vuln/detail/CVE-2025-61592"],
    },
    RuleInfo {
        id: "PT-VSCODE-001",
        name: "VsCodeToolAutoApprove",
        severity: Severity::High,
        category: Category::AgentPermissionOverride,
        title: "VS Code chat tool automatic approval",
        description: "Enables automatic tool execution in .vscode/settings.json bypassing interactive confirmation.",
        agents: &["VS Code", "Copilot"],
        references: &["https://code.visualstudio.com/docs/agents/reference/mcp-configuration"],
    },
    RuleInfo {
        id: "PT-VSCODE-002",
        name: "VsCodeAutomaticTasksAllowed",
        severity: Severity::High,
        category: Category::WorkspaceAutoRun,
        title: "VS Code automatic workspace tasks enabled",
        description: "Enables automatic task execution on folder open via task.allowAutomaticTasks in .vscode/settings.json.",
        agents: &["VS Code"],
        references: &["https://code.visualstudio.com/docs/editor/tasks"],
    },
];

pub fn get_rule(id_or_name: &str) -> Option<&'static RuleInfo> {
    RULES
        .iter()
        .find(|r| r.id == id_or_name || r.name == id_or_name)
}

pub fn all_rules() -> &'static [RuleInfo] {
    RULES
}
